/* Defines the database schema: tables, primary keys, foreign keys, and CHECK constraints. */
-- Stores information about elderly participants.
CREATE TABLE elderly (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    age INT NOT NULL,
    mobility_level VARCHAR(10) NOT NULL,
    notes VARCHAR(500),
    -- Ensures that mobility_level is one of the predefined values.
    CONSTRAINT chk_elderly_mobility_level CHECK (mobility_level IN ('LOW', 'MEDIUM', 'HIGH'))
);

-- Stores information about volunteers.
CREATE TABLE volunteer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

-- Stores walk records between elderly participants and volunteers.
CREATE TABLE walk (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    elderly_id BIGINT NOT NULL,
    volunteer_id BIGINT NOT NULL,
    walk_date DATE NOT NULL,
    duration_minutes INT NOT NULL,
    distance_km DECIMAL (5, 2) NOT NULL,
    pain_mood INT NOT NULL,
    notes VARCHAR(500),
    -- Ensures that pain_mood is within the allowed range.
    CONSTRAINT chk_pain_mood CHECK (
        pain_mood BETWEEN 1
        AND 5
    ),
    CONSTRAINT fk_walk_elderly FOREIGN KEY (elderly_id) REFERENCES elderly(id),
    CONSTRAINT fk_walk_volunteer FOREIGN KEY (volunteer_id) REFERENCES volunteer(id)
);